// @effect-diagnostics globalConsole:off - CLI prints what it vendored.
// @effect-diagnostics globalFetch:off - one-off download outside any Effect runtime.
// @effect-diagnostics nodeBuiltinImport:off - runs directly in Node.
/**
 * Re-pins the vendored FeatureScript Standard Library.
 *
 *   node scripts/vendor-std.ts --commit <sha> --version <n>
 *
 * Downloads the std mirror at `commit`, writes every `*.fs` plus LICENSE.txt into `std/`, replaces the
 * mirror's `✨` version placeholders with the real version, writes `std/VERSION.json` (sha256 per file),
 * and regenerates `src/builtins/stdBuiltinNames.generated.ts` from the `@builtin` calls std makes.
 */
import * as NodeChildProcess from "node:child_process";
import * as NodeCrypto from "node:crypto";
import * as NodeFSP from "node:fs/promises";
import * as NodeOS from "node:os";
import * as NodePath from "node:path";
import * as NodeURL from "node:url";
import * as NodeUtil from "node:util";
import { tokenize } from "../src/syntax/Lexer.ts";
import { sourceFile } from "../src/syntax/Source.ts";

const { values } = NodeUtil.parseArgs({
  options: {
    commit: { type: "string" },
    version: { type: "string" },
    repository: {
      type: "string",
      default: "h0witzer/Onshape-Standard-Library-Mirror-2-Electric-Boogaloo",
    },
  },
});
const { commit, version, repository } = values;
if (!commit || !version || !/^\d+$/.test(version))
  throw new Error("Usage: vendor-std.ts --commit <sha> --version <number>");

const packageDir = NodePath.join(NodePath.dirname(NodeURL.fileURLToPath(import.meta.url)), "..");
const stdDir = NodePath.join(packageDir, "std");
const work = await NodeFSP.mkdtemp(NodePath.join(NodeOS.tmpdir(), "fs-std-"));
try {
  const response = await fetch(`https://codeload.github.com/${repository}/tar.gz/${commit}`);
  if (!response.ok) throw new Error(`Download failed: ${response.status}`);
  await NodeFSP.writeFile(
    NodePath.join(work, "std.tgz"),
    Buffer.from(await response.arrayBuffer()),
  );
  NodeChildProcess.execFileSync("tar", ["-xzf", "std.tgz", "--strip-components=1"], { cwd: work });

  for (const name of await NodeFSP.readdir(stdDir).catch(() => []))
    if (name.endsWith(".fs")) await NodeFSP.rm(NodePath.join(stdDir, name));
  const names = (await NodeFSP.readdir(work)).filter((name) => name.endsWith(".fs")).sort();
  const files: Record<string, string> = {};
  const builtins = new Set<string>();
  for (const name of names) {
    const text = (await NodeFSP.readFile(NodePath.join(work, name), "utf8"))
      .replace(/^FeatureScript ✨;/, `FeatureScript ${version};`)
      .replaceAll(/version\s*:\s*"✨"/g, `version : "${version}.0"`);
    if (text.includes("✨"))
      throw new Error(`${name} has a version placeholder this script doesn't know how to replace`);
    await NodeFSP.writeFile(NodePath.join(stdDir, name), text);
    files[name] = NodeCrypto.createHash("sha256").update(text).digest("hex");
    for (const token of tokenize(sourceFile(name, text)).tokens)
      if (token.kind === "builtin") builtins.add(token.value);
  }
  await NodeFSP.writeFile(
    NodePath.join(stdDir, "LICENSE.txt"),
    await NodeFSP.readFile(NodePath.join(work, "LICENSE.txt")),
  );
  await NodeFSP.writeFile(
    NodePath.join(stdDir, "VERSION.json"),
    `${JSON.stringify({ version: Number(version), repository, commit, files }, null, 2)}\n`,
  );

  const sorted = [...builtins].sort();
  await NodeFSP.writeFile(
    NodePath.join(packageDir, "src/builtins/stdBuiltinNames.generated.ts"),
    [
      `// Generated by scripts/vendor-std.ts from std ${version}. Do not edit.`,
      "/** Every `@builtin` the vendored Standard Library calls. */",
      "export const STD_BUILTIN_NAMES = [",
      ...sorted.map((name) => `  "${name}",`),
      "] as const;",
      "export type StdBuiltinName = (typeof STD_BUILTIN_NAMES)[number];",
      "",
    ].join("\n"),
  );
  console.log(
    `Vendored std ${version} from ${repository}@${commit}: ${names.length} files, ${sorted.length} builtins.`,
  );
} finally {
  await NodeFSP.rm(work, { recursive: true, force: true });
}
