import type { BuiltinImpl } from "../runtime/Interpreter.ts";
import { CONTEXT_BUILTINS } from "./context.ts";
import { CORE_BUILTINS } from "./core.ts";
import type { StdBuiltinName } from "./stdBuiltinNames.generated.ts";

/**
 * Std builtins this runtime doesn't implement yet. Calling one stops the run with a fault that
 * FeatureScript's `try` can't catch. Geometry arrives with the OpenCascade kernel (milestone M4).
 */
const UNSUPPORTED = [
  // Queries and topology
  "clusterBodies",
  "constructPaths",
  "evaluateQuery",
  "evaluateQueryCount",
  "getQueryVariable",
  "isQueryEmpty",
  "lastModifyingOperationId",
  "lastOperationId",
  "queryContainsFlattenedSheetMetal",
  "setQueryVariable",
  "skipOrderDisambiguation",
  "transientIdToString",
  "unpackQuery",
  // Geometry operations
  "opBodyDraft",
  "opBoolean",
  "opBooleanedPattern",
  "opBoundarySurface",
  "opChamfer",
  "opConstrainedSurface",
  "opCreateBSplineCurve",
  "opCreateBSplineSurface",
  "opCreateCompositePart",
  "opCreateCurvesOnFace",
  "opCreateIsocline",
  "opCreateOutline",
  "opDeleteBodies",
  "opDeleteFace",
  "opDerip",
  "opDraft",
  "opDropCurve",
  "opEdgeChange",
  "opEditCurve",
  "opEnclose",
  "opExtendSheetBody",
  "opExtractSurface",
  "opExtractWires",
  "opExtrude",
  "opFaceBlend",
  "opFillSurface",
  "opFillet",
  "opFitSpline",
  "opFlipOrientation",
  "opFullRoundFillet",
  "opHelix",
  "opHole",
  "opImportForeign",
  "opIntersectFaces",
  "opLoft",
  "opMateConnector",
  "opMergeContexts",
  "opModifyCompositePart",
  "opModifyFillet",
  "opMoveCurveBoundary",
  "opMoveFace",
  "opNameEntity",
  "opOffsetCurveOnFace",
  "opOffsetFace",
  "opOffsetWire",
  "opPattern",
  "opPlane",
  "opPoint",
  "opPolyline",
  "opReplaceFace",
  "opRevolve",
  "opRuledSurface",
  "opSMFlatOperation",
  "opShell",
  "opSphere",
  "opSplineThroughEdges",
  "opSplitByIsocline",
  "opSplitBySelfShadow",
  "opSplitEdges",
  "opSplitFace",
  "opSplitPart",
  "opSweep",
  "opTessellatedLoft",
  "opThicken",
  "opTransform",
  "opWrap",
  // Geometry evaluation
  "evApproximateBSplineCurve",
  "evApproximateBSplineSurface",
  "evApproximateCentroid",
  "evApproximateMassProperties",
  "evArea",
  "evAxis",
  "evBox",
  "evCollisionDetection",
  "evCornerType",
  "evCurveDefinition",
  "evDistance",
  "evEdgeConvexity",
  "evEdgeCurvatureDerivatives",
  "evEdgeCurvatures",
  "evEdgeTangentLines",
  "evFaceCurvatureDerivatives",
  "evFaceCurvatures",
  "evFacePeriodicity",
  "evFaceTangentPlanes",
  "evFaceTangentPlanesAtEdge",
  "evFaults",
  "evFilletRadius",
  "evLength",
  "evLine",
  "evMateConnector",
  "evMateConnectorCoordSystem",
  "evMaxPathDeviation",
  "evMaxTolerance",
  "evMeshPoints",
  "evOffsetDetection",
  "evOwnerSketchPlane",
  "evPlanarEdge",
  "evPlanarEdges",
  "evPlane",
  "evPointsDeviation",
  "evRaycast",
  "evRuledSurfaceBases",
  "evSheetMetalBendUp",
  "evSheetMetalFlatTransformation",
  "evSheetMetalFormToolBodies",
  "evSheetMetalHoleToolBodies",
  "evSurfaceDefinition",
  "evTessellatedLoftMatches",
  "evTolerances",
  "evVertexPoint",
  "evVolume",
  "evaluateSpline",
  // Sketches
  "newSketch",
  "skArc",
  "skBezier",
  "skCircle",
  "skConicSegment",
  "skConstraint",
  "skEllipse",
  "skEllipticalArc",
  "skFitSpline",
  "skImage",
  "skInterpolatedSpline",
  "skInterpolatedSplineSegment",
  "skLineSegment",
  "skPoint",
  "skSetInitialGuess",
  "skSolve",
  "skSpline",
  "skSplineSegment",
  "skText",
  // Attributes and properties
  "getAllAttributes",
  "getAttribute",
  "getAttributes",
  "getHoleAttributes",
  "getProperty",
  "removeAttributes",
  "setAttribute",
  "setProperty",
  // Patterns and sheet metal
  "computeCircularPatternTransforms",
  "computeCurvePatternTransforms",
  "computeLinearPatternTransforms",
  "getRemainderPatternTransform",
  "sheetMetalApplyInFlat",
  "updateSheetMetalGeometry",
  // Other
  "alignCanonically",
  "approximateSpline",
  "clampContextVersion",
  "containsSketch",
  "convert",
  "getFeatureName",
  "getLanguageVersion",
  "getParameterToleranceInfo",
  "getTolerantParameterIds",
  "matrixSvd",
  "validateToleranceSchema",
  "valuesSortedById",
] as const satisfies readonly StdBuiltinName[];

/**
 * Every builtin std calls, each either implemented or explicitly unsupported. Re-vendoring std with a
 * new builtin fails the type check here until someone decides which it is.
 */
export const BUILTINS = {
  ...CORE_BUILTINS,
  ...CONTEXT_BUILTINS,
  ...(Object.fromEntries(UNSUPPORTED.map((name) => [name, "unsupported"])) as Record<
    (typeof UNSUPPORTED)[number],
    "unsupported"
  >),
} satisfies Record<StdBuiltinName, BuiltinImpl | "unsupported">;
