// This file is generated by the effect-codex-app-server package. Do not edit manually.
// Upstream protocol ref: 678157acaa819d5510adfe359abb5d0392cfe461

import * as CodexSchema from "./schema.gen.ts";

export const CLIENT_REQUEST_METHODS = {
  initialize: "initialize",
  "thread/start": "thread/start",
  "thread/resume": "thread/resume",
  "thread/read": "thread/read",
  "skills/list": "skills/list",
  "turn/start": "turn/start",
  "turn/interrupt": "turn/interrupt",
  "model/list": "model/list",
  "config/mcpServer/reload": "config/mcpServer/reload",
  "feedback/upload": "feedback/upload",
  "account/read": "account/read",
} as const;

export const CLIENT_NOTIFICATION_METHODS = {
  initialized: "initialized",
} as const;

export const SERVER_REQUEST_METHODS = {
  "item/commandExecution/requestApproval": "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval": "item/fileChange/requestApproval",
  "item/tool/requestUserInput": "item/tool/requestUserInput",
  "mcpServer/elicitation/request": "mcpServer/elicitation/request",
} as const;

export const SERVER_NOTIFICATION_METHODS = {
  error: "error",
  "thread/started": "thread/started",
  "thread/status/changed": "thread/status/changed",
  "thread/archived": "thread/archived",
  "thread/unarchived": "thread/unarchived",
  "thread/closed": "thread/closed",
  "thread/name/updated": "thread/name/updated",
  "thread/settings/updated": "thread/settings/updated",
  "thread/tokenUsage/updated": "thread/tokenUsage/updated",
  "turn/started": "turn/started",
  "turn/completed": "turn/completed",
  "turn/plan/updated": "turn/plan/updated",
  "item/started": "item/started",
  "item/completed": "item/completed",
  "item/agentMessage/delta": "item/agentMessage/delta",
  "item/plan/delta": "item/plan/delta",
  "item/commandExecution/outputDelta": "item/commandExecution/outputDelta",
  "item/commandExecution/terminalInteraction": "item/commandExecution/terminalInteraction",
  "item/fileChange/outputDelta": "item/fileChange/outputDelta",
  "serverRequest/resolved": "serverRequest/resolved",
  "item/mcpToolCall/progress": "item/mcpToolCall/progress",
  "mcpServer/oauthLogin/completed": "mcpServer/oauthLogin/completed",
  "item/reasoning/summaryTextDelta": "item/reasoning/summaryTextDelta",
  "item/reasoning/summaryPartAdded": "item/reasoning/summaryPartAdded",
  "item/reasoning/textDelta": "item/reasoning/textDelta",
  "thread/compacted": "thread/compacted",
  "model/rerouted": "model/rerouted",
  deprecationNotice: "deprecationNotice",
  configWarning: "configWarning",
  "thread/realtime/started": "thread/realtime/started",
  "thread/realtime/itemAdded": "thread/realtime/itemAdded",
  "thread/realtime/outputAudio/delta": "thread/realtime/outputAudio/delta",
  "thread/realtime/error": "thread/realtime/error",
  "thread/realtime/closed": "thread/realtime/closed",
  "windows/worldWritableWarning": "windows/worldWritableWarning",
  "windowsSandbox/setupCompleted": "windowsSandbox/setupCompleted",
} as const;

export type ClientRequestMethod = keyof typeof CLIENT_REQUEST_METHODS;
export type ClientNotificationMethod = keyof typeof CLIENT_NOTIFICATION_METHODS;
export type ServerRequestMethod = keyof typeof SERVER_REQUEST_METHODS;
export type ServerNotificationMethod = keyof typeof SERVER_NOTIFICATION_METHODS;

export interface ClientRequestParamsByMethod {
  readonly initialize: CodexSchema.V1InitializeParams;
  readonly "thread/start": CodexSchema.V2ThreadStartParams;
  readonly "thread/resume": CodexSchema.V2ThreadResumeParams;
  readonly "thread/read": CodexSchema.V2ThreadReadParams;
  readonly "skills/list": CodexSchema.V2SkillsListParams;
  readonly "turn/start": CodexSchema.V2TurnStartParams;
  readonly "turn/interrupt": CodexSchema.V2TurnInterruptParams;
  readonly "model/list": CodexSchema.V2ModelListParams;
  readonly "config/mcpServer/reload": undefined;
  readonly "feedback/upload": CodexSchema.V2FeedbackUploadParams;
  readonly "account/read": CodexSchema.V2GetAccountParams;
}

export interface ClientRequestResponsesByMethod {
  readonly initialize: CodexSchema.V1InitializeResponse;
  readonly "thread/start": CodexSchema.V2ThreadStartResponse;
  readonly "thread/resume": CodexSchema.V2ThreadResumeResponse;
  readonly "thread/read": CodexSchema.V2ThreadReadResponse;
  readonly "skills/list": CodexSchema.V2SkillsListResponse;
  readonly "turn/start": CodexSchema.V2TurnStartResponse;
  readonly "turn/interrupt": CodexSchema.V2TurnInterruptResponse;
  readonly "model/list": CodexSchema.V2ModelListResponse;
  readonly "config/mcpServer/reload": CodexSchema.V2McpServerRefreshResponse;
  readonly "feedback/upload": CodexSchema.V2FeedbackUploadResponse;
  readonly "account/read": CodexSchema.V2GetAccountResponse;
}

export interface ClientNotificationParamsByMethod {
  readonly initialized: undefined;
}

export interface ServerRequestParamsByMethod {
  readonly "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalParams;
  readonly "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalParams;
  readonly "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputParams;
  readonly "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestParams;
}

export interface ServerRequestResponsesByMethod {
  readonly "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalResponse;
  readonly "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalResponse;
  readonly "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputResponse;
  readonly "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestResponse;
}

export interface ServerNotificationParamsByMethod {
  readonly error: CodexSchema.V2ErrorNotification;
  readonly "thread/started": CodexSchema.V2ThreadStartedNotification;
  readonly "thread/status/changed": CodexSchema.V2ThreadStatusChangedNotification;
  readonly "thread/archived": CodexSchema.V2ThreadArchivedNotification;
  readonly "thread/unarchived": CodexSchema.V2ThreadUnarchivedNotification;
  readonly "thread/closed": CodexSchema.V2ThreadClosedNotification;
  readonly "thread/name/updated": CodexSchema.V2ThreadNameUpdatedNotification;
  readonly "thread/settings/updated": CodexSchema.V2ThreadSettingsUpdatedNotification;
  readonly "thread/tokenUsage/updated": CodexSchema.V2ThreadTokenUsageUpdatedNotification;
  readonly "turn/started": CodexSchema.V2TurnStartedNotification;
  readonly "turn/completed": CodexSchema.V2TurnCompletedNotification;
  readonly "turn/plan/updated": CodexSchema.V2TurnPlanUpdatedNotification;
  readonly "item/started": CodexSchema.V2ItemStartedNotification;
  readonly "item/completed": CodexSchema.V2ItemCompletedNotification;
  readonly "item/agentMessage/delta": CodexSchema.V2AgentMessageDeltaNotification;
  readonly "item/plan/delta": CodexSchema.V2PlanDeltaNotification;
  readonly "item/commandExecution/outputDelta": CodexSchema.V2CommandExecutionOutputDeltaNotification;
  readonly "item/commandExecution/terminalInteraction": CodexSchema.V2TerminalInteractionNotification;
  readonly "item/fileChange/outputDelta": CodexSchema.V2FileChangeOutputDeltaNotification;
  readonly "serverRequest/resolved": CodexSchema.V2ServerRequestResolvedNotification;
  readonly "item/mcpToolCall/progress": CodexSchema.V2McpToolCallProgressNotification;
  readonly "mcpServer/oauthLogin/completed": CodexSchema.V2McpServerOauthLoginCompletedNotification;
  readonly "item/reasoning/summaryTextDelta": CodexSchema.V2ReasoningSummaryTextDeltaNotification;
  readonly "item/reasoning/summaryPartAdded": CodexSchema.V2ReasoningSummaryPartAddedNotification;
  readonly "item/reasoning/textDelta": CodexSchema.V2ReasoningTextDeltaNotification;
  readonly "thread/compacted": CodexSchema.V2ContextCompactedNotification;
  readonly "model/rerouted": CodexSchema.V2ModelReroutedNotification;
  readonly deprecationNotice: CodexSchema.V2DeprecationNoticeNotification;
  readonly configWarning: CodexSchema.V2ConfigWarningNotification;
  readonly "thread/realtime/started": CodexSchema.V2ThreadRealtimeStartedNotification;
  readonly "thread/realtime/itemAdded": CodexSchema.V2ThreadRealtimeItemAddedNotification;
  readonly "thread/realtime/outputAudio/delta": CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification;
  readonly "thread/realtime/error": CodexSchema.V2ThreadRealtimeErrorNotification;
  readonly "thread/realtime/closed": CodexSchema.V2ThreadRealtimeClosedNotification;
  readonly "windows/worldWritableWarning": CodexSchema.V2WindowsWorldWritableWarningNotification;
  readonly "windowsSandbox/setupCompleted": CodexSchema.V2WindowsSandboxSetupCompletedNotification;
}

export const CLIENT_REQUEST_PARAMS = {
  initialize: CodexSchema.V1InitializeParams,
  "thread/start": CodexSchema.V2ThreadStartParams,
  "thread/resume": CodexSchema.V2ThreadResumeParams,
  "thread/read": CodexSchema.V2ThreadReadParams,
  "skills/list": CodexSchema.V2SkillsListParams,
  "turn/start": CodexSchema.V2TurnStartParams,
  "turn/interrupt": CodexSchema.V2TurnInterruptParams,
  "model/list": CodexSchema.V2ModelListParams,
  "config/mcpServer/reload": undefined,
  "feedback/upload": CodexSchema.V2FeedbackUploadParams,
  "account/read": CodexSchema.V2GetAccountParams,
} as const;

export const CLIENT_REQUEST_RESPONSES = {
  initialize: CodexSchema.V1InitializeResponse,
  "thread/start": CodexSchema.V2ThreadStartResponse,
  "thread/resume": CodexSchema.V2ThreadResumeResponse,
  "thread/read": CodexSchema.V2ThreadReadResponse,
  "skills/list": CodexSchema.V2SkillsListResponse,
  "turn/start": CodexSchema.V2TurnStartResponse,
  "turn/interrupt": CodexSchema.V2TurnInterruptResponse,
  "model/list": CodexSchema.V2ModelListResponse,
  "config/mcpServer/reload": CodexSchema.V2McpServerRefreshResponse,
  "feedback/upload": CodexSchema.V2FeedbackUploadResponse,
  "account/read": CodexSchema.V2GetAccountResponse,
} as const;

export const CLIENT_NOTIFICATION_PARAMS = {
  initialized: undefined,
} as const;

export const SERVER_REQUEST_PARAMS = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalParams,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalParams,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputParams,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestParams,
} as const;

export const SERVER_REQUEST_RESPONSES = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalResponse,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalResponse,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputResponse,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestResponse,
} as const;

export const SERVER_NOTIFICATION_PARAMS = {
  error: CodexSchema.V2ErrorNotification,
  "thread/started": CodexSchema.V2ThreadStartedNotification,
  "thread/status/changed": CodexSchema.V2ThreadStatusChangedNotification,
  "thread/archived": CodexSchema.V2ThreadArchivedNotification,
  "thread/unarchived": CodexSchema.V2ThreadUnarchivedNotification,
  "thread/closed": CodexSchema.V2ThreadClosedNotification,
  "thread/name/updated": CodexSchema.V2ThreadNameUpdatedNotification,
  "thread/settings/updated": CodexSchema.V2ThreadSettingsUpdatedNotification,
  "thread/tokenUsage/updated": CodexSchema.V2ThreadTokenUsageUpdatedNotification,
  "turn/started": CodexSchema.V2TurnStartedNotification,
  "turn/completed": CodexSchema.V2TurnCompletedNotification,
  "turn/plan/updated": CodexSchema.V2TurnPlanUpdatedNotification,
  "item/started": CodexSchema.V2ItemStartedNotification,
  "item/completed": CodexSchema.V2ItemCompletedNotification,
  "item/agentMessage/delta": CodexSchema.V2AgentMessageDeltaNotification,
  "item/plan/delta": CodexSchema.V2PlanDeltaNotification,
  "item/commandExecution/outputDelta": CodexSchema.V2CommandExecutionOutputDeltaNotification,
  "item/commandExecution/terminalInteraction": CodexSchema.V2TerminalInteractionNotification,
  "item/fileChange/outputDelta": CodexSchema.V2FileChangeOutputDeltaNotification,
  "serverRequest/resolved": CodexSchema.V2ServerRequestResolvedNotification,
  "item/mcpToolCall/progress": CodexSchema.V2McpToolCallProgressNotification,
  "mcpServer/oauthLogin/completed": CodexSchema.V2McpServerOauthLoginCompletedNotification,
  "item/reasoning/summaryTextDelta": CodexSchema.V2ReasoningSummaryTextDeltaNotification,
  "item/reasoning/summaryPartAdded": CodexSchema.V2ReasoningSummaryPartAddedNotification,
  "item/reasoning/textDelta": CodexSchema.V2ReasoningTextDeltaNotification,
  "thread/compacted": CodexSchema.V2ContextCompactedNotification,
  "model/rerouted": CodexSchema.V2ModelReroutedNotification,
  deprecationNotice: CodexSchema.V2DeprecationNoticeNotification,
  configWarning: CodexSchema.V2ConfigWarningNotification,
  "thread/realtime/started": CodexSchema.V2ThreadRealtimeStartedNotification,
  "thread/realtime/itemAdded": CodexSchema.V2ThreadRealtimeItemAddedNotification,
  "thread/realtime/outputAudio/delta": CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification,
  "thread/realtime/error": CodexSchema.V2ThreadRealtimeErrorNotification,
  "thread/realtime/closed": CodexSchema.V2ThreadRealtimeClosedNotification,
  "windows/worldWritableWarning": CodexSchema.V2WindowsWorldWritableWarningNotification,
  "windowsSandbox/setupCompleted": CodexSchema.V2WindowsSandboxSetupCompletedNotification,
} as const;
